// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pipeline.proto

package pipelinepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PipelineOrchestratorService_ExecutePipeline_FullMethodName    = "/pipeline.PipelineOrchestratorService/ExecutePipeline"
	PipelineOrchestratorService_GetPipelineStatus_FullMethodName  = "/pipeline.PipelineOrchestratorService/GetPipelineStatus"
	PipelineOrchestratorService_CancelPipeline_FullMethodName     = "/pipeline.PipelineOrchestratorService/CancelPipeline"
	PipelineOrchestratorService_AddStageToPipeline_FullMethodName = "/pipeline.PipelineOrchestratorService/AddStageToPipeline"
	PipelineOrchestratorService_DeletePipeline_FullMethodName     = "/pipeline.PipelineOrchestratorService/DeletePipeline"
)

// PipelineOrchestratorServiceClient is the client API for PipelineOrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PipelineOrchestratorServiceClient interface {
	ExecutePipeline(ctx context.Context, in *ExecutePipelineRequest, opts ...grpc.CallOption) (*ExecutionResponse, error)
	GetPipelineStatus(ctx context.Context, in *PipelineIDRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	CancelPipeline(ctx context.Context, in *PipelineIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddStageToPipeline(ctx context.Context, in *AddStageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeletePipeline(ctx context.Context, in *PipelineIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type pipelineOrchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPipelineOrchestratorServiceClient(cc grpc.ClientConnInterface) PipelineOrchestratorServiceClient {
	return &pipelineOrchestratorServiceClient{cc}
}

func (c *pipelineOrchestratorServiceClient) ExecutePipeline(ctx context.Context, in *ExecutePipelineRequest, opts ...grpc.CallOption) (*ExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResponse)
	err := c.cc.Invoke(ctx, PipelineOrchestratorService_ExecutePipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineOrchestratorServiceClient) GetPipelineStatus(ctx context.Context, in *PipelineIDRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, PipelineOrchestratorService_GetPipelineStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineOrchestratorServiceClient) CancelPipeline(ctx context.Context, in *PipelineIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PipelineOrchestratorService_CancelPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineOrchestratorServiceClient) AddStageToPipeline(ctx context.Context, in *AddStageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PipelineOrchestratorService_AddStageToPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineOrchestratorServiceClient) DeletePipeline(ctx context.Context, in *PipelineIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PipelineOrchestratorService_DeletePipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PipelineOrchestratorServiceServer is the server API for PipelineOrchestratorService service.
// All implementations must embed UnimplementedPipelineOrchestratorServiceServer
// for forward compatibility.
type PipelineOrchestratorServiceServer interface {
	ExecutePipeline(context.Context, *ExecutePipelineRequest) (*ExecutionResponse, error)
	GetPipelineStatus(context.Context, *PipelineIDRequest) (*StatusResponse, error)
	CancelPipeline(context.Context, *PipelineIDRequest) (*emptypb.Empty, error)
	AddStageToPipeline(context.Context, *AddStageRequest) (*emptypb.Empty, error)
	DeletePipeline(context.Context, *PipelineIDRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPipelineOrchestratorServiceServer()
}

// UnimplementedPipelineOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPipelineOrchestratorServiceServer struct{}

func (UnimplementedPipelineOrchestratorServiceServer) ExecutePipeline(context.Context, *ExecutePipelineRequest) (*ExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecutePipeline not implemented")
}
func (UnimplementedPipelineOrchestratorServiceServer) GetPipelineStatus(context.Context, *PipelineIDRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPipelineStatus not implemented")
}
func (UnimplementedPipelineOrchestratorServiceServer) CancelPipeline(context.Context, *PipelineIDRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPipeline not implemented")
}
func (UnimplementedPipelineOrchestratorServiceServer) AddStageToPipeline(context.Context, *AddStageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStageToPipeline not implemented")
}
func (UnimplementedPipelineOrchestratorServiceServer) DeletePipeline(context.Context, *PipelineIDRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePipeline not implemented")
}
func (UnimplementedPipelineOrchestratorServiceServer) mustEmbedUnimplementedPipelineOrchestratorServiceServer() {
}
func (UnimplementedPipelineOrchestratorServiceServer) testEmbeddedByValue() {}

// UnsafePipelineOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PipelineOrchestratorServiceServer will
// result in compilation errors.
type UnsafePipelineOrchestratorServiceServer interface {
	mustEmbedUnimplementedPipelineOrchestratorServiceServer()
}

func RegisterPipelineOrchestratorServiceServer(s grpc.ServiceRegistrar, srv PipelineOrchestratorServiceServer) {
	// If the following call pancis, it indicates UnimplementedPipelineOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PipelineOrchestratorService_ServiceDesc, srv)
}

func _PipelineOrchestratorService_ExecutePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineOrchestratorServiceServer).ExecutePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineOrchestratorService_ExecutePipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineOrchestratorServiceServer).ExecutePipeline(ctx, req.(*ExecutePipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineOrchestratorService_GetPipelineStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineOrchestratorServiceServer).GetPipelineStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineOrchestratorService_GetPipelineStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineOrchestratorServiceServer).GetPipelineStatus(ctx, req.(*PipelineIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineOrchestratorService_CancelPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineOrchestratorServiceServer).CancelPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineOrchestratorService_CancelPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineOrchestratorServiceServer).CancelPipeline(ctx, req.(*PipelineIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineOrchestratorService_AddStageToPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineOrchestratorServiceServer).AddStageToPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineOrchestratorService_AddStageToPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineOrchestratorServiceServer).AddStageToPipeline(ctx, req.(*AddStageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineOrchestratorService_DeletePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineOrchestratorServiceServer).DeletePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineOrchestratorService_DeletePipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineOrchestratorServiceServer).DeletePipeline(ctx, req.(*PipelineIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PipelineOrchestratorService_ServiceDesc is the grpc.ServiceDesc for PipelineOrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PipelineOrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pipeline.PipelineOrchestratorService",
	HandlerType: (*PipelineOrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecutePipeline",
			Handler:    _PipelineOrchestratorService_ExecutePipeline_Handler,
		},
		{
			MethodName: "GetPipelineStatus",
			Handler:    _PipelineOrchestratorService_GetPipelineStatus_Handler,
		},
		{
			MethodName: "CancelPipeline",
			Handler:    _PipelineOrchestratorService_CancelPipeline_Handler,
		},
		{
			MethodName: "AddStageToPipeline",
			Handler:    _PipelineOrchestratorService_AddStageToPipeline_Handler,
		},
		{
			MethodName: "DeletePipeline",
			Handler:    _PipelineOrchestratorService_DeletePipeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pipeline.proto",
}
