apiVersion: v1
kind: Service
metadata:
  name: authservice-service
spec:
  selector:
    app: authservice
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  # type: ClusterIP  # Change to LoadBalancer if you need external access
