apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudservice
  template:
    metadata:
      labels:
        app: crudservice
    spec:
      containers:
      - name: crudservice
        image: ashwin0711/crudservice:v1
        ports:
        - containerPort: 50054
        env:
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secret
              key: SUPABASE_URL
        - name: ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secret
              key: ANON_KEY
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: supabase-secret
              key: HOST
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: supabase-secret
              key: PORT
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: supabase-secret
              key: DB_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: supabase-secret
              key: DB_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secret
              key: DATABASE_PASSWORD
