apiVersion: v1
kind: Service
metadata:
  name: crudservice-service
spec:
  selector:
    app: crudservice
  ports:
    - protocol: TCP
      port: 50054
      targetPort: 50054
  #     nodePort: 30554  # Choose between 30000-32767
  # type: NodePort