apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80    # This is the Service Port (used inside the cluster)
      targetPort: 80 # Port inside the container
      nodePort: 30001 # Nodeport is for accessing this service from outside of the cluster
  type: NodePort