apiVersion: v1
kind: Service
metadata:
  name: grpcserver-service
spec:
  selector:
    app: grpcserver
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 60000
      nodePort: 30080  # Choose between 30000-32767 - Nodeport is for accessing this service from outside of the cluster
  type: NodePort