apiVersion: v1
kind: Service
metadata:
  name: nats-server  # <-- This must match what your restservice expects
spec:
  selector:
    app: nats
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222