apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelineservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelineservice
  template:
    metadata:
      labels:
        app: pipelineservice
    spec:
      containers:
      - name: pipelineservice
        image: ashwin0711/pipelineservice:v1
        ports:
        - containerPort: 50053
        env:
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: authservice-secret
              key: SUPABASE_URL
        - name: ANON_KEY
          valueFrom:
            secretKeyRef:
              name: authservice-secret
              key: ANON_KEY
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: authservice-secret
              key: HOST
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: authservice-secret
              key: PORT
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: authservice-secret
              key: DB_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: authservice-secret
              key: DB_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authservice-secret
              key: DATABASE_PASSWORD
