apiVersion: v1
kind: Service
metadata:
  name: pipelineservice-service
spec:
  selector:
    app: pipelineservice
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053
  #     nodePort: 30554  # Choose between 30000-32767
  # type: NodePort