apiVersion: v1
kind: Service
metadata:
  name: stageservice-service
spec:
  selector:
    app: stageservice
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
  #     nodePort: 30554  # Choose between 30000-32767
  # type: NodePort